# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: profile

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - qa
          - prod
        description: Deployment environment
      space:
        type: choice
        options:
          - synthetic
          - actual
        description: Deployment environment

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: dev code
      run: python main.py
    - name: qa automation test21
      run: pytest  tests/table21/test_table22.py -v -s
    - name: qa automation test20
      run: pytest  tests/table20/test_table20.py -v -s
